-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.carritodetalles;

CREATE TABLE IF NOT EXISTS public.carritodetalles
(
    id integer NOT NULL DEFAULT nextval('carritodetalles_id_seq'::regclass),
    "Cantidad" integer NOT NULL,
    "Precio" double precision NOT NULL,
    "Tamaño" integer NOT NULL,
    "carritoId" integer,
    "productoId" integer,
    CONSTRAINT carritodetalles_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.carritos;

CREATE TABLE IF NOT EXISTS public.carritos
(
    id integer NOT NULL DEFAULT nextval('carritos_id_seq'::regclass),
    "Total" double precision,
    "userId" integer,
    CONSTRAINT carritos_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.categoria;

CREATE TABLE IF NOT EXISTS public.categoria
(
    id integer NOT NULL DEFAULT nextval('categoria_id_seq'::regclass),
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Descripcion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.detallesordens;

CREATE TABLE IF NOT EXISTS public.detallesordens
(
    id integer NOT NULL DEFAULT nextval('detallesordens_id_seq'::regclass),
    "Cantidad" integer NOT NULL,
    "Tamaño" integer NOT NULL,
    "Precio" double precision NOT NULL,
    "ordenId" integer,
    "productoId" integer,
    CONSTRAINT detallesordens_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.ingredienteproductos;

CREATE TABLE IF NOT EXISTS public.ingredienteproductos
(
    "productoId" integer NOT NULL,
    "ingredienteId" integer NOT NULL,
    CONSTRAINT ingredienteproductos_pkey PRIMARY KEY ("productoId", "ingredienteId")
);

DROP TABLE IF EXISTS public.ingredientes;

CREATE TABLE IF NOT EXISTS public.ingredientes
(
    id integer NOT NULL DEFAULT nextval('ingredientes_id_seq'::regclass),
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ingredientes_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.locals;

CREATE TABLE IF NOT EXISTS public.locals
(
    id integer NOT NULL DEFAULT nextval('locals_id_seq'::regclass),
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Latitud" double precision NOT NULL,
    "Longitud" double precision NOT NULL,
    "Horario" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Direccion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Imagen" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT locals_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.metodopagos;

CREATE TABLE IF NOT EXISTS public.metodopagos
(
    id integer NOT NULL DEFAULT nextval('metodopagos_id_seq'::regclass),
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT metodopagos_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.ordens;

CREATE TABLE IF NOT EXISTS public.ordens
(
    id integer NOT NULL DEFAULT nextval('ordens_id_seq'::regclass),
    "FechaHora" timestamp with time zone NOT NULL,
    "Estatus" integer NOT NULL,
    "Total" double precision NOT NULL,
    "MedioDePago" integer,
    "userId" integer,
    "localId" integer,
    "tarjetaId" integer,
    CONSTRAINT ordens_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.productos;

CREATE TABLE IF NOT EXISTS public.productos
(
    id integer NOT NULL DEFAULT nextval('productos_id_seq'::regclass),
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Descripcion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Precio" double precision NOT NULL,
    "Imagen" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "categoriaId" integer,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.tarjeta;

CREATE TABLE IF NOT EXISTS public.tarjeta
(
    id integer NOT NULL DEFAULT nextval('tarjeta_id_seq'::regclass),
    "NumeroTarjeta" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "FechaVMes" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "FechaVAño" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Codigo" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "NombreTarjeta" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "userId" integer,
    CONSTRAINT tarjeta_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.usuarios;

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id integer NOT NULL DEFAULT nextval('usuarios_id_seq'::regclass),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "emailAddress" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    foto character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.carritodetalles
    ADD CONSTRAINT "carritodetalles_carritoId_fkey" FOREIGN KEY ("carritoId")
    REFERENCES public.carritos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.carritodetalles
    ADD CONSTRAINT "carritodetalles_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.carritos
    ADD CONSTRAINT "carritos_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.detallesordens
    ADD CONSTRAINT "detallesordens_ordenId_fkey" FOREIGN KEY ("ordenId")
    REFERENCES public.ordens (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.detallesordens
    ADD CONSTRAINT "detallesordens_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ingredienteproductos
    ADD CONSTRAINT "ingredienteproductos_ingredienteId_fkey" FOREIGN KEY ("ingredienteId")
    REFERENCES public.ingredientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ingredienteproductos
    ADD CONSTRAINT "ingredienteproductos_productoId_fkey" FOREIGN KEY ("productoId")
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ordens
    ADD CONSTRAINT "ordens_localId_fkey" FOREIGN KEY ("localId")
    REFERENCES public.locals (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ordens
    ADD CONSTRAINT "ordens_tarjetaId_fkey" FOREIGN KEY ("tarjetaId")
    REFERENCES public.tarjeta (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ordens
    ADD CONSTRAINT "ordens_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT "productos_categoriaId_fkey" FOREIGN KEY ("categoriaId")
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tarjeta
    ADD CONSTRAINT "tarjeta_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;